version: 2
updates:
  - package-ecosystem: "npm"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Asia/Tokyo"
    directory: "/financialStatements"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "_"
    rebase-strategy: "auto"
    versioning-strategy: increase
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
      - dependency-name: "typescript"
        versions: ["7.x"]
    groups:
      npm-react-dependencies:
        patterns:
          - "react"
          - "react-dom"
          - "react-is"
  - package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "10:00"
      timezone: "Asia/Tokyo"
    directory: "/"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "_"
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
